import { AccountingSetting, ChartOfAccount } from '@/Features/Accounting/types';

export const mockCoaTree: ChartOfAccount[] = [
    {
        id: 1,
        parent_id: null,
        code: '1000',
        name: 'Aset Lancar',
        display_name: '1000 - Aset Lancar',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 2,
                parent_id: 1,
                code: '1100',
                name: 'Kas & Bank',
                display_name: '1100 - Kas & Bank',
                type: 'asset',
                type_label: 'Aset',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 3,
                        parent_id: 2,
                        code: '1110',
                        name: 'Kas Tunai',
                        display_name: '1110 - Kas Tunai',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                    {
                        id: 4,
                        parent_id: 2,
                        code: '1111',
                        name: 'Bank BCA',
                        display_name: '1111 - Bank BCA',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                    {
                        id: 5,
                        parent_id: 2,
                        code: '1112',
                        name: 'Bank Mandiri',
                        display_name: '1112 - Bank Mandiri',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
            {
                id: 6,
                parent_id: 1,
                code: '1120',
                name: 'Piutang Dagang',
                display_name: '1120 - Piutang Dagang',
                type: 'asset',
                type_label: 'Aset',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 7,
                        parent_id: 6,
                        code: '1121',
                        name: 'Piutang Dagang Client',
                        display_name: '1121 - Piutang Dagang Client',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
            {
                id: 8,
                parent_id: 1,
                code: '1130',
                name: 'Uang Muka',
                display_name: '1130 - Uang Muka',
                type: 'asset',
                type_label: 'Aset',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 9,
                        parent_id: 8,
                        code: '1131',
                        name: 'Uang Muka / DP dari Client',
                        display_name: '1131 - Uang Muka / DP dari Client',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
            {
                id: 10,
                parent_id: 1,
                code: '1140',
                name: 'Pajak Dibayar Muka',
                display_name: '1140 - Pajak Dibayar Muka',
                type: 'asset',
                type_label: 'Aset',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 11,
                        parent_id: 10,
                        code: '1141',
                        name: 'PPN Masukan',
                        display_name: '1141 - PPN Masukan',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'ppn_only',
                        fiscal_mode_context_label: 'Hanya Mode PPN',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                    {
                        id: 12,
                        parent_id: 10,
                        code: '1142',
                        name: 'PPh Dibayar Muka',
                        display_name: '1142 - PPh Dibayar Muka',
                        type: 'asset',
                        type_label: 'Aset',
                        normal_balance: 'debit',
                        normal_balance_label: 'Debet',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
        ],
    },
    {
        id: 13,
        parent_id: null,
        code: '2000',
        name: 'Kewajiban Lancar',
        display_name: '2000 - Kewajiban Lancar',
        type: 'liability',
        type_label: 'Kewajiban',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 14,
                parent_id: 13,
                code: '2100',
                name: 'Hutang Usaha',
                display_name: '2100 - Hutang Usaha',
                type: 'liability',
                type_label: 'Kewajiban',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 15,
                        parent_id: 14,
                        code: '2110',
                        name: 'Hutang Dagang Vendor',
                        display_name: '2110 - Hutang Dagang Vendor',
                        type: 'liability',
                        type_label: 'Kewajiban',
                        normal_balance: 'credit',
                        normal_balance_label: 'Kredit',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
            {
                id: 16,
                parent_id: 13,
                code: '2120',
                name: 'Hutang Pajak',
                display_name: '2120 - Hutang Pajak',
                type: 'liability',
                type_label: 'Kewajiban',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: false,
                children: [
                    {
                        id: 17,
                        parent_id: 16,
                        code: '2121',
                        name: 'PPN Keluaran',
                        display_name: '2121 - PPN Keluaran',
                        type: 'liability',
                        type_label: 'Kewajiban',
                        normal_balance: 'credit',
                        normal_balance_label: 'Kredit',
                        fiscal_mode_context: 'ppn_only',
                        fiscal_mode_context_label: 'Hanya Mode PPN',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                    {
                        id: 18,
                        parent_id: 16,
                        code: '2122',
                        name: 'Hutang PPh Pemotongan',
                        display_name: '2122 - Hutang PPh Pemotongan',
                        type: 'liability',
                        type_label: 'Kewajiban',
                        normal_balance: 'credit',
                        normal_balance_label: 'Kredit',
                        fiscal_mode_context: 'all',
                        fiscal_mode_context_label: 'Semua Mode',
                        level: 3,
                        is_active: true,
                        is_leaf: true,
                    },
                ],
            },
        ],
    },
    {
        id: 19,
        parent_id: null,
        code: '3000',
        name: 'Ekuitas',
        display_name: '3000 - Ekuitas',
        type: 'equity',
        type_label: 'Ekuitas',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 20,
                parent_id: 19,
                code: '3100',
                name: 'Modal Disetor',
                display_name: '3100 - Modal Disetor',
                type: 'equity',
                type_label: 'Ekuitas',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 21,
                parent_id: 19,
                code: '3200',
                name: 'Laba Ditahan',
                display_name: '3200 - Laba Ditahan',
                type: 'equity',
                type_label: 'Ekuitas',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
        ],
    },
    {
        id: 22,
        parent_id: null,
        code: '4000',
        name: 'Pendapatan',
        display_name: '4000 - Pendapatan',
        type: 'revenue',
        type_label: 'Pendapatan',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 23,
                parent_id: 22,
                code: '4110',
                name: 'Pendapatan Billboard',
                display_name: '4110 - Pendapatan Billboard',
                type: 'revenue',
                type_label: 'Pendapatan',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 24,
                parent_id: 22,
                code: '4120',
                name: 'Pendapatan Videotron',
                display_name: '4120 - Pendapatan Videotron',
                type: 'revenue',
                type_label: 'Pendapatan',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 25,
                parent_id: 22,
                code: '4130',
                name: 'Pendapatan Cetak / Produksi',
                display_name: '4130 - Pendapatan Cetak / Produksi',
                type: 'revenue',
                type_label: 'Pendapatan',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 26,
                parent_id: 22,
                code: '4190',
                name: 'Pendapatan Lain-lain',
                display_name: '4190 - Pendapatan Lain-lain',
                type: 'revenue',
                type_label: 'Pendapatan',
                normal_balance: 'credit',
                normal_balance_label: 'Kredit',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
        ],
    },
    {
        id: 27,
        parent_id: null,
        code: '5000',
        name: 'Beban Pokok Pendapatan (HPP)',
        display_name: '5000 - Beban Pokok Pendapatan (HPP)',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 28,
                parent_id: 27,
                code: '5110',
                name: 'HPP Billboard',
                display_name: '5110 - HPP Billboard',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 29,
                parent_id: 27,
                code: '5120',
                name: 'HPP Videotron',
                display_name: '5120 - HPP Videotron',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 30,
                parent_id: 27,
                code: '5200',
                name: 'HPP Cetak / Produksi',
                display_name: '5200 - HPP Cetak / Produksi',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
        ],
    },
    {
        id: 31,
        parent_id: null,
        code: '6000',
        name: 'Beban Operasional',
        display_name: '6000 - Beban Operasional',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 1,
        is_active: true,
        is_leaf: false,
        children: [
            {
                id: 32,
                parent_id: 31,
                code: '6110',
                name: 'Beban Gaji & Tunjangan',
                display_name: '6110 - Beban Gaji & Tunjangan',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 33,
                parent_id: 31,
                code: '6120',
                name: 'Beban Sewa',
                display_name: '6120 - Beban Sewa',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 34,
                parent_id: 31,
                code: '6130',
                name: 'Beban Perlengkapan Kantor',
                display_name: '6130 - Beban Perlengkapan Kantor',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
            {
                id: 35,
                parent_id: 31,
                code: '6190',
                name: 'Beban Operasional Lain-lain',
                display_name: '6190 - Beban Operasional Lain-lain',
                type: 'expense',
                type_label: 'Beban',
                normal_balance: 'debit',
                normal_balance_label: 'Debet',
                fiscal_mode_context: 'all',
                fiscal_mode_context_label: 'Semua Mode',
                level: 2,
                is_active: true,
                is_leaf: true,
            },
        ],
    },
];

export const mockLeafAccounts: ChartOfAccount[] = [
    {
        id: 3,
        parent_id: 2,
        code: '1110',
        name: 'Kas Tunai',
        display_name: '1110 - Kas Tunai',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 4,
        parent_id: 2,
        code: '1111',
        name: 'Bank BCA',
        display_name: '1111 - Bank BCA',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 5,
        parent_id: 2,
        code: '1112',
        name: 'Bank Mandiri',
        display_name: '1112 - Bank Mandiri',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 7,
        parent_id: 6,
        code: '1121',
        name: 'Piutang Dagang Client',
        display_name: '1121 - Piutang Dagang Client',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 9,
        parent_id: 8,
        code: '1131',
        name: 'Uang Muka / DP dari Client',
        display_name: '1131 - Uang Muka / DP dari Client',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 11,
        parent_id: 10,
        code: '1141',
        name: 'PPN Masukan',
        display_name: '1141 - PPN Masukan',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'ppn_only',
        fiscal_mode_context_label: 'Hanya Mode PPN',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 12,
        parent_id: 10,
        code: '1142',
        name: 'PPh Dibayar Muka',
        display_name: '1142 - PPh Dibayar Muka',
        type: 'asset',
        type_label: 'Aset',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 15,
        parent_id: 14,
        code: '2110',
        name: 'Hutang Dagang Vendor',
        display_name: '2110 - Hutang Dagang Vendor',
        type: 'liability',
        type_label: 'Kewajiban',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 17,
        parent_id: 16,
        code: '2121',
        name: 'PPN Keluaran',
        display_name: '2121 - PPN Keluaran',
        type: 'liability',
        type_label: 'Kewajiban',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'ppn_only',
        fiscal_mode_context_label: 'Hanya Mode PPN',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 18,
        parent_id: 16,
        code: '2122',
        name: 'Hutang PPh Pemotongan',
        display_name: '2122 - Hutang PPh Pemotongan',
        type: 'liability',
        type_label: 'Kewajiban',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 3,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 20,
        parent_id: 19,
        code: '3100',
        name: 'Modal Disetor',
        display_name: '3100 - Modal Disetor',
        type: 'equity',
        type_label: 'Ekuitas',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 21,
        parent_id: 19,
        code: '3200',
        name: 'Laba Ditahan',
        display_name: '3200 - Laba Ditahan',
        type: 'equity',
        type_label: 'Ekuitas',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 23,
        parent_id: 22,
        code: '4110',
        name: 'Pendapatan Billboard',
        display_name: '4110 - Pendapatan Billboard',
        type: 'revenue',
        type_label: 'Pendapatan',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 24,
        parent_id: 22,
        code: '4120',
        name: 'Pendapatan Videotron',
        display_name: '4120 - Pendapatan Videotron',
        type: 'revenue',
        type_label: 'Pendapatan',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 25,
        parent_id: 22,
        code: '4130',
        name: 'Pendapatan Cetak / Produksi',
        display_name: '4130 - Pendapatan Cetak / Produksi',
        type: 'revenue',
        type_label: 'Pendapatan',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 26,
        parent_id: 22,
        code: '4190',
        name: 'Pendapatan Lain-lain',
        display_name: '4190 - Pendapatan Lain-lain',
        type: 'revenue',
        type_label: 'Pendapatan',
        normal_balance: 'credit',
        normal_balance_label: 'Kredit',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 28,
        parent_id: 27,
        code: '5110',
        name: 'HPP Billboard',
        display_name: '5110 - HPP Billboard',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 29,
        parent_id: 27,
        code: '5120',
        name: 'HPP Videotron',
        display_name: '5120 - HPP Videotron',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 30,
        parent_id: 27,
        code: '5200',
        name: 'HPP Cetak / Produksi',
        display_name: '5200 - HPP Cetak / Produksi',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 32,
        parent_id: 31,
        code: '6110',
        name: 'Beban Gaji & Tunjangan',
        display_name: '6110 - Beban Gaji & Tunjangan',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 33,
        parent_id: 31,
        code: '6120',
        name: 'Beban Sewa',
        display_name: '6120 - Beban Sewa',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 34,
        parent_id: 31,
        code: '6130',
        name: 'Beban Perlengkapan Kantor',
        display_name: '6130 - Beban Perlengkapan Kantor',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
    {
        id: 35,
        parent_id: 31,
        code: '6190',
        name: 'Beban Operasional Lain-lain',
        display_name: '6190 - Beban Operasional Lain-lain',
        type: 'expense',
        type_label: 'Beban',
        normal_balance: 'debit',
        normal_balance_label: 'Debet',
        fiscal_mode_context: 'all',
        fiscal_mode_context_label: 'Semua Mode',
        level: 2,
        is_active: true,
        is_leaf: true,
    },
];

export const mockAccountingSettings: AccountingSetting[] = [
    {
        id: 1,
        key: 'default_receivable_account_id',
        description: 'Akun Piutang Dagang default saat Invoice diterbitkan',
        chart_of_account_id: 7,
        chart_of_account: mockLeafAccounts.find((a) => a.id === 7)!,
    },
    {
        id: 2,
        key: 'default_payable_account_id',
        description: 'Akun Hutang Dagang default saat PO dibuat',
        chart_of_account_id: 15,
        chart_of_account: mockLeafAccounts.find((a) => a.id === 15)!,
    },
    {
        id: 3,
        key: 'default_vat_in_account_id',
        description: 'Akun PPN Masukan (hanya aktif di transaksi mode PPN)',
        chart_of_account_id: 11,
        chart_of_account: mockLeafAccounts.find((a) => a.id === 11)!,
    },
    {
        id: 4,
        key: 'default_vat_out_account_id',
        description: 'Akun PPN Keluaran (hanya aktif di transaksi mode PPN)',
        chart_of_account_id: 17,
        chart_of_account: mockLeafAccounts.find((a) => a.id === 17)!,
    },
    {
        id: 5,
        key: 'default_pph_payable_account_id',
        description: 'Akun Hutang PPh untuk pemotongan pajak penghasilan',
        chart_of_account_id: 18,
        chart_of_account: mockLeafAccounts.find((a) => a.id === 18)!,
    },
];
