import { ClientPaymentPlan, Project } from './projectTypes';

// ─────────────────────────────────────────────────────────────────────────────
// Master Data Vendors
// ─────────────────────────────────────────────────────────────────────────────
export const mockVendors = [
    { id: 1, name: 'PT. Megah Billboard Jaya' },
    { id: 2, name: 'CV. Media Ad Perkasa' },
    { id: 3, name: 'PT. Promosi Outdoor Kreasindo' },
    { id: 4, name: 'UD. Spanduk & Baliho Makmur' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Master Data Clients
// ─────────────────────────────────────────────────────────────────────────────
export const mockClients = [
    { id: 1, name: 'PT. Walt Disney Pictures Indonesia' },
    { id: 2, name: 'Shopee Indonesia' },
    { id: 3, name: 'PT. Gojek Tokopedia' },
    { id: 4, name: 'CV. Soto Bangkong Lestari' },
    { id: 5, name: 'Samsung Electronics Indonesia' },
    { id: 6, name: 'Sari Laundry Express' },
    { id: 7, name: 'PT. Pakuwon Jati Tbk' },
    { id: 8, name: 'PT. Tokopedia' },
    { id: 9, name: 'PT. Ecart Webportal Indonesia (Lazada)' },
    { id: 10, name: 'Dinas Pariwisata Kota Semarang' },
    { id: 11, name: 'Pemkab Klaten' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Master Data Sales PIC
// ─────────────────────────────────────────────────────────────────────────────
export const mockSalesPICs = [
    'Budi Santoso',
    'Rina Widayanti',
    'Andi Prasetyo',
    'Eko Prasetyo',
    'Rian Hidayat',
    'Siti Aminah',
];

// ─────────────────────────────────────────────────────────────────────────────
// Initial Projects (PPN Mode)
// ─────────────────────────────────────────────────────────────────────────────
export const initialProjectsPPN: Project[] = [
    {
        id: 1,
        targetQty: 3,
        code: 'PRJ-2026-PPN01',
        name: 'Kampanye Iklan Film Toystory 5 - Jawa Tengah',
        clientId: 1,
        clientName: 'PT. Walt Disney Pictures Indonesia',
        salesPIC: 'Budi Santoso',
        period: '01 Apr - 30 Jun 2026',
        contractValue: 280000000,
        status: 'Completed',
        invoiceIssued: true,
        invoiceNumber: 'INV-PTSSI/04/2026/001',
        clientPaymentPlan: {
            scheme: 'full',
            totalAmount: 280000000 * 1.11,
            notes: 'Pembayaran penuh via transfer bank BCA',
            createdAt: '2026-04-01',
            terms: [
                {
                    id: 't1-1',
                    label: 'Lunas Sekaligus',
                    amount: 280000000 * 1.11,
                    percent: 100,
                    dueDate: '2026-04-30',
                    status: 'paid',
                    paidAt: '2026-04-28',
                    notes: 'Transfer BCA konfirmasi 28 Apr 2026',
                },
            ],
        } as ClientPaymentPlan,
        locations: [
            {
                id: 1,
                code: 'LOC-001',
                area: 'Semarang',
                description: 'Billboard Jl. Pandanaran KM 3 (Megah)',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 8500000,
                poIssued: true,
                poNumber: '001/PTSSI-PO/04/26',
            },
            {
                id: 2,
                code: 'LOC-002',
                area: 'Solo',
                description: 'Videotron Jl. Slamet Riyadi Pusat',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 22000000,
                poIssued: true,
                poNumber: '002/PTSSI-PO/04/26',
            },
            {
                id: 5,
                code: 'LOC-005',
                area: 'Yogyakarta',
                description: 'Billboard Ring Road Utara Monjali',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 9000000,
                poIssued: true,
                poNumber: '003/PTSSI-PO/04/26',
            },
        ],
    },
    {
        id: 2,
        targetQty: 4,
        code: 'PRJ-2026-PPN02',
        name: 'Grand Opening Pakuwon Mall Yogyakarta',
        clientId: 7,
        clientName: 'PT. Pakuwon Jati Tbk',
        salesPIC: 'Rina Widayanti',
        period: '15 Jun - 15 Agu 2026',
        contractValue: 390000000,
        status: 'Active',
        invoiceIssued: false,
        invoiceNumber: '',
        clientPaymentPlan: {
            scheme: 'termin',
            totalAmount: 390000000 * 1.11,
            notes: '3 termin sesuai progres pemasangan',
            createdAt: '2026-06-15',
            terms: [
                {
                    id: 't2-1',
                    label: 'Termin 1 – Uang Muka',
                    amount: Math.round(390000000 * 1.11 * 0.3),
                    percent: 30,
                    dueDate: '2026-06-20',
                    status: 'paid',
                    paidAt: '2026-06-19',
                    notes: 'DP awal sebelum pemasangan',
                },
                {
                    id: 't2-2',
                    label: 'Termin 2 – Setelah Pemasangan',
                    amount: Math.round(390000000 * 1.11 * 0.4),
                    percent: 40,
                    dueDate: '2026-07-10',
                    status: 'paid',
                    paidAt: '2026-07-09',
                    notes: 'Setelah seluruh titik terpasang',
                },
                {
                    id: 't2-3',
                    label: 'Termin 3 – Pelunasan Akhir',
                    amount: Math.round(390000000 * 1.11 * 0.3),
                    percent: 30,
                    dueDate: '2026-08-15',
                    status: 'unpaid',
                    notes: 'Pelunasan akhir periode',
                },
            ],
        } as ClientPaymentPlan,
        locations: [
            {
                id: 6,
                code: 'LOC-006',
                area: 'Yogyakarta',
                description: 'Billboard Ring Road Selatan KM 2',
                type: 'Billboard',
                size: '6x12m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 18000000,
                poIssued: true,
                poNumber: '004/PTSSI-PO/06/26',
            },
            {
                id: 7,
                code: 'LOC-007',
                area: 'Yogyakarta',
                description: 'Videotron Jl. Laksda Adisucipto',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 21000000,
                poIssued: true,
                poNumber: '005/PTSSI-PO/06/26',
            },
            {
                id: 8,
                code: 'LOC-008',
                area: 'Solo',
                description: 'Billboard Jl. Adi Sucipto KM 7',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 12000000,
                poIssued: true,
                poNumber: '004/PTSSI-PO/06/26',
            },
            {
                id: 9,
                code: 'LOC-009',
                area: 'Semarang',
                description: 'Neonbox Jl. Pemuda (Depan Paragon)',
                type: 'Neonbox',
                size: '2x3m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 7500000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
    {
        id: 3,
        targetQty: 5,
        code: 'PRJ-2026-PPN03',
        name: 'Harbolnas 8.8 Tokopedia - Jawa Tengah & DIY',
        clientId: 8,
        clientName: 'PT. Tokopedia',
        salesPIC: 'Budi Santoso',
        period: '01 Jul - 31 Agu 2026',
        contractValue: 520000000,
        status: 'Active',
        invoiceIssued: false,
        invoiceNumber: '',
        clientPaymentPlan: {
            scheme: 'dp',
            totalAmount: 520000000 * 1.11,
            notes: 'DP 40% sebelum mulai, pelunasan setelah kampanye',
            createdAt: '2026-07-01',
            terms: [
                {
                    id: 't3-1',
                    label: 'DP 40%',
                    amount: Math.round(520000000 * 1.11 * 0.4),
                    percent: 40,
                    dueDate: '2026-07-05',
                    status: 'paid',
                    paidAt: '2026-07-04',
                    notes: 'Transfer BNI rekening perusahaan',
                },
                {
                    id: 't3-2',
                    label: 'Pelunasan 60%',
                    amount: Math.round(520000000 * 1.11 * 0.6),
                    percent: 60,
                    dueDate: '2026-09-01',
                    status: 'unpaid',
                    notes: 'Pelunasan setelah kampanye selesai 31 Agu',
                },
            ],
        } as ClientPaymentPlan,
        locations: [
            {
                id: 10,
                code: 'LOC-010',
                area: 'Semarang',
                description: 'Billboard Simpang Lima (Depan BCA)',
                type: 'Billboard',
                size: '6x12m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 14000000,
                poIssued: true,
                poNumber: '006/PTSSI-PO/07/26',
            },
            {
                id: 11,
                code: 'LOC-011',
                area: 'Semarang',
                description: 'Videotron Jl. Pahlawan',
                type: 'Videotron',
                size: '4x8m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 19000000,
                poIssued: true,
                poNumber: '007/PTSSI-PO/07/26',
            },
            {
                id: 12,
                code: 'LOC-012',
                area: 'Solo',
                description: 'Videotron Jl. Slamet Riyadi Pusat',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 22000000,
                poIssued: true,
                poNumber: '007/PTSSI-PO/07/26',
            },
            {
                id: 13,
                code: 'LOC-013',
                area: 'Yogyakarta',
                description: 'Baliho Jl. Malioboro (Dekat Kraton)',
                type: 'Baliho',
                size: '3x6m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 7500000,
                poIssued: true,
                poNumber: '008/PTSSI-PO/07/26',
            },
            {
                id: 14,
                code: 'LOC-014',
                area: 'Yogyakarta',
                description: 'Billboard Ring Road Utara Monjali',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 9000000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
    {
        id: 4,
        targetQty: 2,
        code: 'PRJ-2026-PPN04',
        name: 'Brand Awareness Shopee 9.9 - Jawa Tengah',
        clientId: 2,
        clientName: 'Shopee Indonesia',
        salesPIC: 'Rina Widayanti',
        period: '01 Agu - 30 Sep 2026',
        contractValue: 340000000,
        status: 'Active',
        invoiceIssued: false,
        invoiceNumber: '',
        locations: [
            {
                id: 15,
                code: 'LOC-015',
                area: 'Semarang',
                description: 'Billboard Jl. Pemuda (Dekat Paragon Mall)',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 9500000,
                poIssued: true,
                poNumber: '009/PTSSI-PO/08/26',
            },
            {
                id: 16,
                code: 'LOC-016',
                area: 'Solo',
                description: 'Videotron Solo Grand Mall',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 15000000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
    {
        id: 5,
        targetQty: 2,
        code: 'PRJ-2026-PPN05',
        name: 'Samsung Galaxy S27 Launching - Jabodetabek',
        clientId: 5,
        clientName: 'Samsung Electronics Indonesia',
        salesPIC: 'Budi Santoso',
        period: '01 Okt - 31 Des 2026',
        contractValue: 720000000,
        status: 'Draft',
        invoiceIssued: false,
        invoiceNumber: '',
        locations: [
            {
                id: 17,
                code: 'LOC-017',
                area: 'Solo',
                description: 'Videotron Jl. Slamet Riyadi Pusat',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 22000000,
                poIssued: false,
                poNumber: '',
            },
            {
                id: 18,
                code: 'LOC-018',
                area: 'Semarang',
                description: 'Videotron Jl. Pahlawan',
                type: 'Videotron',
                size: '4x8m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 19000000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
    {
        id: 6,
        targetQty: 3,
        code: 'PRJ-2026-PPN06',
        name: 'Harbolnas 12.12 Lazada - Nasional',
        clientId: 9,
        clientName: 'PT. Ecart Webportal Indonesia (Lazada)',
        salesPIC: 'Rina Widayanti',
        period: '01 Nov - 31 Des 2026',
        contractValue: 680000000,
        status: 'Draft',
        invoiceIssued: false,
        invoiceNumber: '',
        locations: [
            {
                id: 19,
                code: 'LOC-019',
                area: 'Semarang',
                description: 'Billboard Jl. Pandanaran KM 3',
                type: 'Billboard',
                size: '6x12m',
                vendorId: 1,
                vendorName: 'PT. Megah Billboard Jaya',
                vendorCost: 16000000,
                poIssued: false,
                poNumber: '',
            },
            {
                id: 20,
                code: 'LOC-020',
                area: 'Solo',
                description: 'Baliho Jl. Slamet Riyadi (Bundaran Gladak)',
                type: 'Baliho',
                size: '4x8m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 8500000,
                poIssued: false,
                poNumber: '',
            },
            {
                id: 21,
                code: 'LOC-021',
                area: 'Yogyakarta',
                description: 'Videotron Jl. Laksda Adisucipto',
                type: 'Videotron',
                size: '3x5m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 21000000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// Initial Projects (Non-PPN Mode)
// ─────────────────────────────────────────────────────────────────────────────
export const initialProjectsNonPPN: Project[] = [
    {
        id: 101,
        targetQty: 1,
        code: 'PRJ-2026-NON01',
        name: 'Papan Nama Neonbox Laundry Express - Yogya',
        clientId: 6,
        clientName: 'Sari Laundry Express',
        salesPIC: 'Andi Prasetyo',
        period: '01 Mar - 31 Mei 2026',
        contractValue: 12500000,
        status: 'Completed',
        invoiceIssued: true,
        invoiceNumber: 'INV/03/2026/001',
        paymentTerms: {
            type: 'full',
            fullDueDays: 30,
            notes: 'Pembayaran 100% dalam 30 hari setelah invoice diterima',
        },
        clientPaymentPlan: {
            scheme: 'full',
            totalAmount: 12500000,
            notes: 'Bayar lunas transfer bank',
            createdAt: '2026-03-01',
            terms: [
                {
                    id: 't101-1',
                    label: 'Lunas Sekaligus',
                    amount: 12500000,
                    percent: 100,
                    dueDate: '2026-03-31',
                    status: 'paid',
                    paidAt: '2026-03-29',
                    notes: 'Transfer BCA - sudah konfirmasi',
                },
            ],
        } as ClientPaymentPlan,
        locations: [
            {
                id: 108,
                code: 'LOC-108',
                area: 'Yogyakarta',
                description: 'Neonbox Perempatan Tugu Yogyakarta',
                type: 'Neonbox',
                size: '2x3m',
                vendorId: 2,
                vendorName: 'CV. Media Ad Perkasa',
                vendorCost: 4500000,
                poIssued: true,
                poNumber: '001/YS-PO/03/26',
            },
        ],
    },
    {
        id: 102,
        targetQty: 2,
        code: 'PRJ-2026-NON02',
        name: 'Spanduk Festival Kuliner Semarang 2026',
        clientId: 10,
        clientName: 'Dinas Pariwisata Kota Semarang',
        salesPIC: 'Eko Prasetyo',
        period: '01 Apr - 31 Mei 2026',
        contractValue: 55000000,
        status: 'Completed',
        invoiceIssued: true,
        invoiceNumber: 'INV/04/2026/002',
        locations: [
            {
                id: 109,
                code: 'LOC-109',
                area: 'Semarang',
                description: 'Baliho Kawasan Kota Lama',
                type: 'Baliho',
                size: '3x6m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 6000000,
                poIssued: true,
                poNumber: '002/YS-PO/04/26',
            },
            {
                id: 110,
                code: 'LOC-110',
                area: 'Semarang',
                description: 'Spanduk Jl. Pandanaran depan Simpang Lima',
                type: 'Baliho',
                size: '2x4m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 3200000,
                poIssued: true,
                poNumber: '002/YS-PO/04/26',
            },
        ],
    },
    {
        id: 103,
        targetQty: 3,
        code: 'PRJ-2026-NON03',
        name: 'Promosi Gojek UMKM - Jawa Timur',
        clientId: 3,
        clientName: 'PT. Gojek Tokopedia',
        salesPIC: 'Andi Prasetyo',
        period: '01 Jun - 31 Agu 2026',
        contractValue: 180000000,
        status: 'Active',
        invoiceIssued: false,
        invoiceNumber: '',
        locations: [
            {
                id: 111,
                code: 'LOC-111',
                area: 'Surabaya',
                description: 'Baliho Jl. Darmo (Depan Taman Bungkul)',
                type: 'Baliho',
                size: '3x6m',
                vendorId: 3,
                vendorName: 'PT. Promosi Outdoor Kreasindo',
                vendorCost: 5500000,
                poIssued: true,
                poNumber: '003/YS-PO/06/26',
            },
            {
                id: 112,
                code: 'LOC-112',
                area: 'Malang',
                description: 'Billboard Jl. Kahuripan (Alun-alun Kota)',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 4200000,
                poIssued: true,
                poNumber: '004/YS-PO/06/26',
            },
            {
                id: 113,
                code: 'LOC-113',
                area: 'Banyuwangi',
                description: 'Neonbox Terminal Blambangan',
                type: 'Neonbox',
                size: '1.5x2m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 2800000,
                poIssued: false,
                poNumber: '',
            },
        ],
    },
    {
        id: 104,
        targetQty: 2,
        code: 'PRJ-2026-NON04',
        name: 'Iklan Pemkab Klaten - HUT RI ke-81',
        clientId: 11,
        clientName: 'Pemkab Klaten',
        salesPIC: 'Eko Prasetyo',
        period: '01 Jul - 31 Agu 2026',
        contractValue: 48000000,
        status: 'Active',
        invoiceIssued: false,
        invoiceNumber: '',
        locations: [
            {
                id: 114,
                code: 'LOC-114',
                area: 'Klaten',
                description: 'Billboard Alun-alun Klaten',
                type: 'Billboard',
                size: '4x8m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 5000000,
                poIssued: true,
                poNumber: '005/YS-PO/07/26',
            },
            {
                id: 115,
                code: 'LOC-115',
                area: 'Klaten',
                description: 'Spanduk Jl. Pemuda (Rute Karnaval)',
                type: 'Baliho',
                size: '1x5m',
                vendorId: 4,
                vendorName: 'UD. Spanduk & Baliho Makmur',
                vendorCost: 1800000,
                poIssued: true,
                poNumber: '005/YS-PO/07/26',
            },
        ],
    },
];
